_target_: gan.model.GAN
latent_size: 16
discriminator_steps: 2
discriminator_loss_log_steps: 100
generator_loss_log_steps: 10
train_log_images_steps: 100
log_norm_steps: 500
generator:
  _target_: torch.nn.Sequential
  _args_:
    - _target_: gan.model.ExpandLatentSpace
      width: ${dataset.width}
      height: ${dataset.height}
    - _target_: gan.model.PositionalEmbedding
      width: ${dataset.width}
      height: ${dataset.height}
      channels: ${model.latent_size}
    - _target_: torch.nn.Conv2d
      in_channels: ${model.latent_size}
      out_channels: 16
      kernel_size: 3
      padding: 1
    - _target_: torch.nn.LeakyReLU
    - _target_: torch.nn.Conv2d
      in_channels: 16
      out_channels: 32
      kernel_size: 3
      padding: 1
    - _target_: torch.nn.LeakyReLU
    - _target_: torch.nn.Conv2d
      in_channels: 32
      out_channels: 32
      kernel_size: 3
      padding: 1
    - _target_: torch.nn.LeakyReLU
    - _target_: torch.nn.Conv2d
      in_channels: 32
      out_channels: 32
      kernel_size: 3
      padding: 1
    - _target_: torch.nn.LeakyReLU
    - _target_: torch.nn.Conv2d
      in_channels: 32
      out_channels: ${dataset.input_channels}
      kernel_size: 3
      padding: 1
    - _target_: torch.nn.Tanh
discriminator:
  _target_: torch.nn.Sequential
  _args_:
    - _target_: torch.nn.Conv2d
      in_channels: ${dataset.input_channels}
      out_channels: 16
      kernel_size: 3
      padding: 1
    - _target_: torch.nn.LeakyReLU
    - _target_: torch.nn.Conv2d
      in_channels: 16
      out_channels: 16
      kernel_size: 3
      padding: 1
    - _target_: torch.nn.LeakyReLU
    - _target_: torch.nn.Conv2d
      in_channels: 16
      out_channels: 16
      kernel_size: 3
      padding: 1
    - _target_: torch.nn.LeakyReLU
    - _target_: torch.nn.Conv2d
      in_channels: 16
      out_channels: 16
      kernel_size: 3
      stride: 2
      padding: 1
    - _target_: torch.nn.LeakyReLU
    - _target_: torch.nn.Conv2d
      in_channels: 16
      out_channels: 16
      kernel_size: 3
      padding: 1
    - _target_: torch.nn.LeakyReLU
    - _target_: torch.nn.Conv2d
      in_channels: 16
      out_channels: 16
      kernel_size: 3
      padding: 1
      stride: 2
    - _target_: torch.nn.LeakyReLU
    - _target_: torch.nn.Conv2d
      in_channels: 16
      out_channels: 16
      kernel_size: 3
      padding: 1
      stride: 2
    - _target_: torch.nn.LeakyReLU
    - _target_: torch.nn.Conv2d
      in_channels: 16
      out_channels: 1
      kernel_size: 3
      padding: 1
      stride: 2
    - _target_: torch.nn.LeakyReLU
    - _target_: torch.nn.Flatten
      start_dim: 1  #bs, 1
    - _target_: torch.nn.Sigmoid